import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuLinks = [
    { href: '/imoveis', label: 'Imóveis' },
    { href: '/imoveis/criar', label: 'Cadastrar Imóvel' },
    { href: '/locadores/criar', label: 'Cadastrar Locador' },
    { href: '/locatarios/criar', label: 'Cadastrar Locatário' },
    { href: '/templates', label: 'Templates de Contrato' },
    { href: '/contratos', label: 'Contratos' },
    { href: '/contratos/gerar', label: 'Gerar Contrato' },
  ];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div style={{ display: 'flex', minHeight: '100vh' }}>
          <aside className="menu-lateral">
            <nav>
              {menuLinks.map(link => (
                <a key={link.href} href={link.href}>
                  {link.label}
                </a>
              ))}
            </nav>
          </aside>
          <main style={{ flex: 1 }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
